import {
  readJson,
  readdir,
  mkdirp,
  pathExists,
  writeFile,
  ensureDir,
} from "fs-extra";
import download from "download";

import { join } from "path";

const getPhotos = async () => {
  await mkdirp(join(".", "attachments"));
  const files = (await readdir(join("."))).filter((i) => i.endsWith(".json"));
  const images: any[] = [];
  for await (const file of files) {
    const json = await readJson(join(".", file));
    if (Array.isArray(json)) {
      json.forEach((i) => {
        ["pictures", "distributionPictures"].forEach((j) => {
          if (i[j])
            images.push({
              type: file.replace(".json", ""),
              typeKey: j,
              data: i[j],
            });
        });
      });
    }
  }
  let i = 0;
  for await (const item of images) {
    for await (const image of item.data) {
      i++;
      if (i > 5) break;
      const url = `attachments/${item.type}/${image.id}`;
      const hasImage = await pathExists(join(".", url));
      if (true) {
        for await (const key of Object.keys(image.thumbnails || {})) {
          const img = (image.thumbnails || {})[key];
          console.log(img);
          // const file = await axios.get(img.url);
        }
        await ensureDir(join(".", url));
        await writeFile(
          join(".", url, "README.md"),
          `# Image \`${image.id}\`

## Original file details

- **ID:** ${image.id}
- **URL:** ${image.url}
- **File name:** ${image.filename}
- **Size:** ${image.size}
- **Type:** ${image.type}
- **Thumbnails:**
${Object.keys(image.thumbnails || {})
  .map(
    (i) =>
      `  - [${i.charAt(0).toUpperCase() + i.slice(1)}](${
        image.thumbnails[i].url
      }) (${image.thumbnails[i].width}×${image.thumbnails[i].height})`
  )
  .join("\n")}

## Generated file details

${Object.keys(image.thumbnails || {})
  .map(
    (i) =>
      `- ${i.charAt(0).toUpperCase() +
        i.slice(1)}: https://open-data.karuna2020.org/${url}/${i}.${(
        image.type || ""
      ).replace("image/", "")}`
  )
  .join("\n")}

_This file is automatically generated, please don't edit it manually._

`
        );
      }
    }
  }
};

getPhotos();
